AMQP_URI: amqp://${RABBIT_USER:guest}:${RABBIT_PASSWORD:guest}@${RABBIT_HOST:localhost}:${RABBIT_PORT:5672}/
PRODUCT_IMAGE_ROOT: "http://www.example.com/airship/images"
DB_URIS:
    "orders:Base": postgresql://${DB_USER:postgres}:${DB_PASSWORD:postgres}@${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:orders}
REDIS_URI: ${REDIS_URI:"redis://localhost:6379/dev"}
